Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path

from .views import (home, category_list, category_blogs,
                    tag_blogs, blog_detail, login_page, logout_page,
                    register, blog_create, blog_update, blog_delete, user_list, about_page)

urlpatterns = [
    path('', home, name='home'),
    path('categories/', category_list, name='category_list'),
    path('category/<slug:slug>', category_blogs, name='category_blogs'),
    path('tag/<slug:slug>', tag_blogs, name='tag_blogs'),
    path('blog/<slug:slug>', blog_detail, name='blog_detail'),
    path('register', register, name='register'),
    path('login', login_page, name='login_page'),
    path('logout', logout_page, name='logout_page'),
    path('create/', blog_create, name='blog_create'),
    path('update/<slug:slug>', blog_update, name='blog_update'),
    path('delete/<slug:slug>', blog_delete, name='blog_delete'),
    path('users', user_list, name='user_list'),
    path('about', about_page, name='about_page'),

]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='category/')
    description = models.TextField()

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    views = models.PositiveBigIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Blog, Comment

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class BlogForm(forms.ModelForm):
    tags = forms.CharField(max_length=255)
    class Meta:
        model = Blog
        fields = ['title', 'description', 'image', 'category']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

myapp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator

from .models import Blog, Category, Tag
from .forms import RegisterForm, BlogForm, CommentForm


def home(request):
    blogs = Blog.objects.all()

    paginator = Paginator(blogs, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'blogs': page_obj,
    }

    return render(request, 'home.html', context)


def category_list(request):
    categories = Category.objects.all()

    context = {
        'categories': categories,
    }

    return render(request, 'category_list.html', context)


def category_blogs(request, slug):
    category = Category.objects.get(slug=slug)
    blogs = Blog.objects.filter(category=category)

    context = {
        'category': category,
        'blogs': blogs
    }

    return render(request, 'category_blogs.html', context)


def tag_blogs(request, slug):
    tag = Tag.objects.get(slug=slug)
    blogs = Blog.objects.filter(tags=tag)

    context = {
        'tag': tag,
        'blogs': blogs,
    }

    return render(request, 'tag_blogs.html', context)


def blog_detail(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form_commnet = form.save(commit=False)
            form_commnet.blog = blog
            form_commnet.user = request.user
            form_commnet.save()
            return redirect('blog_detail', blog.slug)
    else:
        form = CommentForm()

    blog.views += 1
    blog.save()

    context = {
        'blog': blog,
        'form': form,
    }

    return render(request, 'blog_detail.html', context)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = RegisterForm()

    context = {
        'form': form
    }

    return render(request, 'register_page.html', context)


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'username or password error!')
            return redirect('login_page')

    return render(request, 'login_page.html')


def logout_page(request):
    logout(request)
    return redirect('home')


@login_required(login_url='login_page')
def blog_create(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES or None)
        if form.is_valid():
            form2 = form.save(commit=False)
            form2.slug = slugify(form2.title)
            form2.user = request.user
            form2.save()
            blog = Blog.objects.get(id=form2.id)
            tags_req = form.cleaned_data.get('tags')
            tag_list = list(tags_req.split(','))
            for t in tag_list:
                t, created = Tag.objects.get_or_create(name=t.strip())
                blog.tags.add(t)
            return redirect('home')
    else:
        form = BlogForm()

    context = {
        'form': form
    }

    return render(request, 'blog_create.html', context)


def blog_update(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    form = BlogForm(request.POST or None, instance = blog)
    if form.is_valid():
        form2 = form.save(commit=False)
        form2.slug = slugify(form2.title)
        form2.save()
        tags_req = form.cleaned_data.get('tags')
        tag_list = list(tags_req.split(','))
        for t in tag_list:
            t, created = Tag.objects.get_or_create(name=t.strip())
            blog.tags.add(t)
        return redirect('blog_detail', blog.slug)

    context = {
        'blog': blog,
        'form': form,
    }

    return render(request, 'blog_update.html', context)


def blog_delete(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    if request.method == 'POST':
        blog.delete()
        return redirect('home')

    context = {
        'blog':blog
    }

    return render(request, 'blog_delete.html', context)


def user_list(request):
    username = request.GET.get('username')
    if username:
        users = User.objects.filter(username__icontains=username)
    else:
        users = User.objects.all()

    context = {
        'users': users
    }

    return render(request, 'user_list.html', context)

def about_page(request):
    return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block content %}
<br>
<br>    

<h3>This Blog was created  by UralovDEV </h3>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">MyBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'category_list' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'user_list' %}" class="nav-link active">Users</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'blog_create' %}" class="nav-link active">Blog Add</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'about_page' %}" class="nav-link active">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav  mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a  class="nav-link active">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout_page' %}" class="nav-link active">Chiqish</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login_page' %}" class="nav-link active">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'register' %}" class="nav-link active">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <div class="row">
        <div class="col-lg-9">
            {% block content %}

            {% endblock %}
        </div>
        <div class="col-lg-3">
            <h1>Categories All</h1>
            <hr>
            {% for category in categories %}
                <p><a href="{% url 'category_blogs' category.slug %}">{{ category.name }}</a></p>
            {% endfor %}

            <h1>Top blogs</h1>
            <hr>
            {% for tb in top_blogs %}
                <p><a href="{% url 'blog_detail' tb.slug %}">{{ tb.title }} </a></p>
            {% endfor %}

            <h1>Tags All</h1>
            <hr>
            {% for tag in tags %}
                <a href="{% url 'tag_blogs' tag.slug %}">#{{ tag.name }} </a>
            {% endfor %}
        </div>
    </div>
</div>
<footer>
    Footer
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}

{% block title %} Create {% endblock %}

{% block content %}
    <h1>Blog create page</h1>
    <hr></hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Blog</button>
    </form>

{% endblock %}

templates/blog_delete.html
{% extends 'base.html' %}

{% block title %} Delete {% endblock %}

{% block content %}
    <h1>{{ blog.title }} delete page</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Delete Blog</button>
    </form>
    <a href="{% url 'blog_detail' blog.slug %}">Orqaga</a>

{% endblock %}

templates/blog_detail.html
{% extends 'base.html' %}

{% block title %} {{ blog.title }} home {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">

            <h1>{{ blog.title }} page</h1>
            <hr>
            <h3>{{ blog.title }}</h3>
            <p><a href="{% url 'category_blogs' blog.category.slug %}">{{ blog.category.name }}</a>
                Sana: {{ blog.created | date:'Y-m-d // h:i' }}</p>
            <img style="width: 800px;" src="{{ blog.image.url }}" alt="Bu rasm">
            <p>{{ blog.description }}</p>
            <p>User: {{ blog.user.username }}</p>
            <p>Ko'rishlar soni: {{ blog.views }}</p>
            {% for tag in blog.tags.all %}
                <a href="{% url 'tag_blogs' tag.slug %}">#{{ tag.name }} </a>
            {% endfor %}
            <br>
            {% if blog.user == request.user %}
                <a href="{% url 'blog_update' blog.slug %}"> Update </a>
                <a href="{% url 'blog_delete' blog.slug %}"> Delete </a>
            {% endif %}

        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            {% for comment in blog.comment_set.all %}
                <p>User: {{ comment.user.username }} | Date: {{ comment.created }}</p>
                <p>{{ comment.text }}</p>
                <hr>
            {% endfor %}
        </div>
        <div class="col-lg-6">
            <form method="post">
                {% csrf_token %}
                <label>Izoh qoldiring!</label>
                {{ form.text }}
                {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-primary">Comment</button>
                {% else %}
                    <a href="{% url 'login_page' %}" class="btn btn-primary">Comment</a>
                {% endif %}
            </form>
        </div>
    </div>

{% endblock %}

templates/blog_update.html
{% extends 'base.html' %}

{% block title %} Update {% endblock %}

{% block content %}
    <h1>{{ blog.title }} update page</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update Blog</button>
    </form>

{% endblock %}

templates/category_blogs.html
{% extends 'base.html' %}

{% block title %} {{ category.name }} home {% endblock %}

{% block content %}

    <h1>{{ category.name }} page</h1>
    <hr>
    {% for blog in blogs %}
        <h3><a href="{% url 'blog_detail' blog.slug %}">{{ blog.title }}</a></h3>
        <p><a href="{% url 'category_blogs' blog.category.slug %}">{{ blog.category.name }}</a>
            Sana: {{ blog.created | date:'Y-m-d // h:i' }}</p>
        <img style="width: 400px;" src="{{ blog.image.url }}" alt="Bu rasm">
        <p>{{ blog.description | truncatechars:100 }}</p>
        <p>User: {{ blog.user.username }}</p>
        <p>Ko'rishlar soni: {{ blog.views }}</p>
        {% for tag in blog.tags.all %}
            <a href="{% url 'tag_blogs' tag.slug %}">#{{ tag.name }} </a>
        {% endfor %}
        <hr>
    {% endfor %}
{% endblock %}

templates/category_list.html
{% extends 'base.html' %}

{% block title %} Category home {% endblock %}

{% block content %}
    <h1>Categories All</h1>
    <hr>
    {% for category in categories %}
        <div class="row">
            <div class="col-lg-5">
                <img style="width: 200px;" src="{{ category.image.url }}">
            </div>
            <div class="col-lg-7">
                <h3><a href="{% url 'category_blogs' category.slug %}">{{ category.name }}</a></h3>
                <p>{{ category.description }}</p>
                <p>Blogs count: {{ category.blog_set.count }}</p>
            </div>
        </div>
        <hr>
    {% endfor %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %} Blog home {% endblock %}

{% block content %}

    <h1>Home page</h1>
    <hr>
    {% for blog in blogs %}
        <h3><a href="{% url 'blog_detail' blog.slug %}">{{ blog.title }}</a></h3>
        <p><a href="{% url 'category_blogs' blog.category.slug %}">{{ blog.category.name }}</a>
            Sana: {{ blog.created | date:'Y-m-d // h:i' }}</p>
        <img style="width: 400px;" src="{{ blog.image.url }}" alt="Bu rasm">
        <p>{{ blog.description | truncatechars:100 }}</p>
        <p>User: {{ blog.user.username }}</p>
        <p>Ko'rishlar soni: {{ blog.views }}</p>
        {% for tag in blog.tags.all %}
            <a href="{% url 'tag_blogs' tag.slug %}">#{{ tag.name }} </a>
        {% endfor %}
        <hr>
    {% endfor %}

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if blogs.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ blogs.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% for i in blogs.paginator.page_range %}
                <li class="{% if i == blogs.number %}page-item active{% else %}page-item{% endif %}">
                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                </li>
            {% endfor %}
            {% if blogs.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ blogs.next_page_number }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/login_page.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    {% for mess in messages %}
        {% if mess %}
            <div class="alert alert-danger" role="alert">
                {{ mess }}
            </div>
        {% endif %}
    {% endfor %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="exampleInputUsername">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

{% endblock %}

templates/register_page.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %} Register {% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Username</label>
            {% render_field form.username  class="form-control" %}
        </div>
        <div class="mb-3">
            <label  class="form-label">Email</label>
            {% render_field form.email  class="form-control" %}
        </div>
        <div class="mb-3">
            <label  class="form-label">Password</label>
            {% render_field form.password1  class="form-control" %}
        </div>
        <div class="mb-3">
            <label  class="form-label">Password confirm</label>
            {% render_field form.password2  class="form-control" %}
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>

{% endblock %}

templates/tag_blogs.html
{% extends 'base.html' %}

{% block title %} {{ tag.name }} home {% endblock %}

{% block content %}

    <h1>{{ tag.name }} page</h1>
    <hr>
    {% for blog in blogs %}
        <h3><a href="{% url 'blog_detail' blog.slug %}">{{ blog.title }}</a></h3>
        <p><a href="{% url 'category_blogs' blog.category.slug %}">{{ blog.category.name }}</a>
            Sana: {{ blog.created | date:'Y-m-d // h:i' }}</p>
        <img style="width: 400px;" src="{{ blog.image.url }}" alt="Bu rasm">
        <p>{{ blog.description | truncatechars:100 }}</p>
        <p>User: {{ blog.user.username }}</p>
        <p>Ko'rishlar soni: {{ blog.views }}</p>
        {% for tag in blog.tags.all %}
            <a href="{% url 'tag_blogs' tag.slug %}">#{{ tag.name }} </a>
        {% endfor %}
        <hr>
    {% endfor %}
{% endblock %}

templates/user_list.html
{% extends 'base.html' %}

{% block title %} Users list {% endblock %}

{% block content %}
    <h1>Users list</h1>
    <hr>
    <form method="get">
    <input name="username" placeholder="username">
    <button type="submit">Search</button>
    </form>
    <hr>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Date Joined</th>
      <th scope="col">Last login </th>
    </tr>
  </thead>
  <tbody>
  {% for user in users %}
    <tr>
      <th scope="row">{{ user.id }}</th>
      <td>{{ user.username }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.date_joined }}</td>
      <td>{{ user.last_login }}</td>
    </tr>
  {% endfor %}

  </tbody>
</table>

{% endblock %}